name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - xarray
  - scipy
  - voila
  - kagglehub
  - ipywidgets
  - pandas
  - matplotlib
  - ipympl
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - climada=5.0.0
  - climada-petals=5.0.0
