name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - voila
  - kagglehub
  - ipywidgets
  - pandas
  - matplotlib
  - ipympl
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - climada=5.0.0=pyhd8ed1ab_2
  - ipympl
  - pip:
      - climada-petals==5.0.0
